# Generated by Django 6.0.7 on 2026-07-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(default='FLOOR_WORKER', max_length=50)),
                ('query', models.TextField()),
                ('language', models.CharField(default='hi', max_length=10)),
                ('response', models.TextField()),
                ('sources_used', models.JSONField(default=list)),
                ('access_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GENERAL_SAFETY', 'General Plant Safety & Guidelines'), ('BLAST_FURNACE', 'Blast Furnace SOPs & Operations'), ('MAINTENANCE', 'Heavy Machinery Maintenance'), ('QUALITY_CONTROL', 'Steel Quality & Testing SOPs'), ('MARKETING_SALES', 'Confidential Marketing & Sales Data')], default='GENERAL_SAFETY', max_length=50)),
                ('required_department', models.CharField(choices=[('FLOOR_WORKER', 'Floor Worker / Operator'), ('PLANT_ENGINEER', 'Plant Maintenance Engineer'), ('MARKETING_SALES', 'Marketing & Sales Executive'), ('ADMIN', 'Factory Administrator')], default='FLOOR_WORKER', help_text='Minimum department required to access this document in RAG', max_length=50)),
                ('content', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_confidential', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('required_department', models.CharField(default='FLOOR_WORKER', max_length=50)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat_rag.document')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('FLOOR_WORKER', 'Floor Worker / Operator'), ('PLANT_ENGINEER', 'Plant Maintenance Engineer'), ('MARKETING_SALES', 'Marketing & Sales Executive'), ('ADMIN', 'Factory Administrator')], default='FLOOR_WORKER', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
