# Generated by Django 6.0.1 on 2026-08-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rag', '0002_documentchunk_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='required_department',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer (CEO)'), ('QC', 'Quality Control Inspector (QC)')], default='QC', help_text='Minimum department required to access this document in RAG', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='required_department',
            field=models.CharField(default='QC', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CEO', 'Chief Executive Officer (CEO)'), ('QC', 'Quality Control Inspector (QC)')], default='CEO', max_length=50),
        ),
    ]
